packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/**/*'

catalog:
  'rollup-plugin-visualizer': 5.12.0
  'react': ^18.3.1
  'react-dom': ^18.3.1
  'react-i18next': ^14.1.0
  '@tanstack/react-query': 5.62.7
  '@tanstack/react-query-devtools': 5.59.13
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  '@types/react': ^18.2.33
  '@types/react-dom': ^18.2.14
  '@types/node': ^22.9.1
  'react-hook-form': ^7.53.0
  'vite': ^5.4.11
  '@vitejs/plugin-react': ^4.3.2
  'typescript': ^5.6.3
  'prettier': ^3.3.3
  'vite-plugin-dts': ^4.1.0
  'turbo': ^2.3.1
  '@react-spring/web': ^9.7.5
  'clsx': ^2.1.1
  'eslint': ^9.12.0
  '@eslint/js': ^9.12.0
  'eslint-plugin-react-hooks': 5.1.0-rc.0
  'eslint-plugin-react-refresh': ^0.4.12
  'typescript-eslint': ^8.8.1
  'msw': ^2.3.1
  '@tiptap/core': '2.11.0'
