export type CommonColor =
  | 'black'
  | 'gray-800'
  | 'gray-700'
  | 'gray-600'
  | 'gray-500'
  | 'gray-400'
  | 'gray-300'
  | 'gray-200'
  | 'white'
  | 'danger'
  | 'warning'
  | 'success'
  | 'info'
  | 'danger-800'
  | 'warning-800'
  | 'success-800'
  | 'info-800'
  | 'danger-300'
  | 'warning-300'
  | 'success-300'
  | 'info-300'
  | 'danger-200'
  | 'warning-200'
  | 'success-200'
  | 'info-200'
  | 'accessible-blue'
  | 'accessible-deep-blue'
  | 'accessible-pink'
  | 'accessible-salamander'
  | 'accessible-sunshade'
  | 'accessible-yellow';

export type ThemeColor =
  | 'primary'
  | 'primary-800'
  | 'primary-300'
  | 'primary-200'
  | 'secondary'
  | 'secondary-800'
  | 'secondary-300'
  | 'secondary-200';

export type Color = CommonColor | ThemeColor;
